server:
  port: 4003

spring:
  application:
    name: order

  data:
    mongodb:
      uri: mongodb://localhost:27017/mydb

  cache:
    type: redis
    redis:
      time-to-live: '3600000'
  redis:
    host: localhost
    port: '6379'

  devtools:
    restart:
      enabled: 'true'
    livereload:
      enabled: 'true'