groups:
  - name: instance_down
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Instance Down"
          description: "L'instance {{ $labels.instance }} est inaccessible."

  - name: high_cpu_usage
    rules:
      - alert: HighCPUUsage
        expr: process_cpu_seconds_total > 0.7
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "CPU élevé"
          description: "Le CPU utilisé dépasse 70% sur {{ $labels.instance }}."

  - name: high_memory_usage
    rules:
      - alert: HighMemoryUsage
        expr: process_resident_memory_bytes > 1000000000
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Mémoire élevée"
          description: "La mémoire RAM utilisée dépasse 1GB."

  - name: postgres_errors
    rules:
      - alert: PostgreSQLTooManyConnections
        expr: pg_stat_activity_count > 100
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "PostgreSQL trop de connexions"
          description: "Plus de 100 connexions ouvertes sur PostgreSQL."

  - name: rabbitmq_queue_overload
    rules:
      - alert: RabbitMQQueueTooLong
        expr: rabbitmq_queue_messages > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Queue RabbitMQ trop longue"
          description: "Plus de 1000 messages en attente."
