global:
  resolve_timeout: 5m

route:
  receiver: 'telegram'
  group_wait: 15s
  group_interval: 1m
  repeat_interval: 10m

receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token: '7393622191:AAGJinuwWBKahgSzGdUL59kR_vzH1YuWbPs'
        chat_id: 5516457807
        message: '{{ range .Alerts }}{{ .Annotations.summary }}: {{ .Annotations.description }}\n{{ end }}'

#  - name: 'slack'
#    slack_configs:
#      - api_url: 'https://hooks.slack.com/services/TOKEN'
#        channel: '#alerts'
#        text: '{{ range .Alerts }}{{ .Annotations.summary }}: {{ .Annotations.description }}\n{{ end }}'
#
#  - name: 'email'
#    email_configs:
#      - to: 'admin@example.com'
#        from: 'alertmanager@example.com'
#        smarthost: 'smtp.example.com:587'
#        auth_username: 'user'
#        auth_password: 'password'
