services:
  postgres:
    image: postgres:16-alpine
    # container_name: postgres-db-vehicle
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: 123123123
      # POSTGRES_DB: vehicle_service
      POSTGRES_USER: root
    volumes:
      - ./pgdata:/var/lib/postgresql/data