global:
  resolve_timeout: 5m

route:
  receiver: 'telegram'
  group_wait: 15s
  group_interval: 1m
  repeat_interval: 10m

receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token: '7393622191:AAGJinuwWBKahgSzGdUL59kR_vzH1YuWbPs'
        chat_id: 5516457807
        message: '{{ range .Alerts }}{{ .Annotations.summary }}: {{ .Annotations.description }}\n{{ end }}'