# global:
#   scrape_interval: 15s # scrape interval

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "./alert.rules.yml"

scrape_configs:
  - job_name: app
    scrape_interval: 60s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8080']

  - job_name: node_exporter
    scrape_interval: 60s
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: prometheus
    scrape_interval: 30s
    static_configs:
      - targets: ['prometheus:9090']
    
  - job_name: tempo
    scrape_interval: 30s
    static_configs:
      - targets: ['tempo:3200']
  
  - job_name: loki
    scrape_interval: 30s
    static_configs:
      - targets: ['loki:3100']

  - job_name: alertmanager
    scrape_interval: 30s
    static_configs:
      - targets: ['alertmanager:9093']
  
  - job_name: grafana
    scrape_interval: 30s
    static_configs:
      - targets: ['grafana:3000']
  