#
#logging:
#  config: classpath:logback-prod.xml
#  pattern:
#    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
#  level:
#    com:
#      example:
#        product: INFO
#    root: INFO
#  file:
#    path: 'src/main/resources/logs'
#    name: prod-product.log


logging:
  file:
    name: logs/product_app.log
  level:
    root: INFO
