server:
  port: 4002


spring:
  application:
    name: product

  datasource: # Posgreql
    url: jdbc:postgresql://localhost:5432/mydb # jdbc:postgresql://localhost:5432/mydb
    username: myuser
    password: password
    driverClassName: org.postgresql.Driver

  jpa: # Posgreql + Hibernate ORM
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update #create-drop #validate create-drop
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway: # Migration => SQL
    baselineOnMigrate: true
    enabled: true
    locations: classpath:db.migration
    baseline-on-migrate: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    baseline-version: 0
    baseline-description: "init"

  cache: # Redis => CACHE
    type: redis
    data:
      redis:
        host: localhost # localhost
        port: 6379 # 6379
        password:
        time-to-live: 3600000  # Cache TTL (1 hour)

  # select profile => dev | Prod
  profiles:
    active: prod

# Monitoring
javamelody:
  enabled: true
  excluded-datasources: secretSource,topSecretSource
  spring-monitoring-enabled: true
  init-parameters:
    log: false

# Monitoring (prometheus) => /actuator/prometheus
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: 'true'
  endpoint:
    prometheus:
      enabled: 'true'
    health:
      show-details: always
    metrics:
      enabled: 'true'
