# dev conf => logging (logs will appear in the console when running locally).
logging:

  level:
    org:
      springframework: INFO
    com:
      example:
        product: DEBUG
    root: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
