services:
  postgres:
    image: postgres:16-alpine
    # container_name: postgres-db-rent
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: 123123123
      POSTGRES_DB: rent_service
      POSTGRES_USER: root
    volumes:
      - ./pgdata:/var/lib/postgresql/data